blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import DataListView, DescriptionDetailView, BlogCreateView, BlogUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path('', DataListView.as_view(), name='data'),
    path('blog/', BlogCreateView.as_view(), name='create'),
    path('desc/<int:pk>', DescriptionDetailView.as_view(), name='desc'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update')
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import DataListView, DescriptionDetailView

app_name = CatalogConfig.name

urlpatterns = [
    path('', DataListView.as_view(), name='data'),
    path('desc/<int:pk>', DescriptionDetailView.as_view(), name='desc'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    content = models.CharField(max_length=555, verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='превью', **NULLABLE)
    date_cr = models.DateField(verbose_name='дата создания', **NULLABLE)
    publication_sign = models.BooleanField(default=True, verbose_name="опубликовано")
    views_counter = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title} {self.content} {self.preview} {self.slug}'

    class Meta:
        ordering = ('title',)

catalog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.CharField(max_length=100, verbose_name='описание')
    image = models.ImageField(upload_to='product/', verbose_name='превью', **NULLABLE)
    category = models.CharField(max_length=100, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена')
    date_cr = models.DateField(verbose_name='дата создания', **NULLABLE)
    date_ch = models.DateField(verbose_name='дата последнего изменения', **NULLABLE)

    def __str__(self):
        return f'{self.name} | описание: {self.description}\n {self.category}\n {self.price}'

    class Meta:
        ordering = ('name',)

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.CharField(max_length=100, verbose_name='описание')

    def __str__(self):
        return f'{self.name} | описание: {self.description}'

    class Meta:
        ordering = ('name',)

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from pytils.translit import slugify

from blog.models import Blog



class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'preview')
    success_url = reverse_lazy('blog:data')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview')

    def get_success_url(self):
        return reverse('blog:desc', args=[self.object.pk])


class DataListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication_sign=True)
        return queryset


class DescriptionDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object

catalog/views.py
from django.views.generic import ListView, DetailView

from catalog.models import Product
from django.shortcuts import render


class BaseListView(ListView):
    model = Product
    template_name = 'catalog/base.html'


class DataListView(ListView):
    model = Product
    template_name = 'catalog/data.html'


class DescriptionDetailView(DetailView):
    model = Product
    template_name = 'catalog/desc.html'

# def base(request):
#     Product_list = Product.objects.all()
#     content = {
#         'object_list': Product_list,
#         'title': 'Каталог',
#         'description': 'Ну тут всё прям для тебя',
#     }
#     return render(request, 'catalog/base.html', content)

# def data(request):
#     Product_list = Product.objects.all()
#     content = {
#         'object_list': Product_list,
#         'title': 'Каталог',
#         'description': 'Ну тут всё прям для тебя',
#     }
#     return render(request, 'catalog/data.html', content)

# def description(request, pk):
#     Description_list = Product.objects.get(pk=pk)
#     content = {
#         'object_list': Description_list,
#         'title': 'Описание',
#         'description': 'Коротко и понятно'
#     }
#     return render(request, 'catalog/desc.html', content)

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<title>Описание</title>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Написать отзыв</a>
</div>
<div class="card-deck mb-3 text-center">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal"> "{{ object.title }}"</h4>
             <div class="card mb-3 box-shadow">
                <h4 class="my-0 font-weight-normal"> "{{ object.content }}"</h4>
                <h4 class="my-0 font-weight-normal"> {{ object.slug }}
             </div>
            <h4 class="my-0 font-weight-normal"> Просмотры: {{ object.views_counter }}</h4>
            <img class="mb-2" src="{{ object.preview }}" alt="">
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}

        <div class="col-12">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p}}
                                <button type="submit" class="btn btn-success">Опубликовать</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load custom_tags %}
{% block content %}

    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Написать отзыв</a>
    </div>
    <div class="row">
        {% for object in object_list%}
        <div class="col-md-4 card-deck mb-2 text-center">
            <div class="card mb-3 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    <a href="{% url 'blog:update' object.pk %}" class="btn btn-sm btn-outline-secondary">Редактировать отзыв</a>
                    <a href="{% url 'blog:desc' object.pk %}" class="btn btn-sm btn-outline-secondary">Открыть отзыв</a>
                </div>
                <div class="card-body">
                    <img class="mb-2" src="{{ object.preview|mediapath }}" alt="" width="400" height="400">
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
{% load custom_tags %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> {{ title }} </title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
</head>

<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <h5 class="my-0 mr-md-auto font-weight-normal">Магазин "У помоечки"</h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="#">Тут ничего нет</a>
            <a class="p-2 text-dark" href="#">И тут пусто</a>
            <a class="p-2 text-dark" href="#">Надежда умирает последней?</a>
        </nav>
        <a class="btn btn-outline-primary" href="{% url 'catalog:data' %}">Главная страница!!!</a>
    </div>

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ title }}</h1>
        <p class="lead">{{ description }}</p>
    </div>
</body>
    {% block content %}
    {% endblock %}
</div>
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <img class="mb-2" src="{{ 'icon.jpg'|mediapath }}" alt="" width="100" height="100">
        </div>
        <div class="col-6 col-md">
            <h5>Тут можно оставить отзыв</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'blog:data' %}">Отзывы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Какая-то нужная часть сайта</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Это тоже</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Какая-то нужная часть сайта</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">И это</a></li>
            </ul>
        </div>
    </div>
</footer>



<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/vendor/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/vendor/holder.min.js' %}"></script>
<script>
    Holder.addTheme('thumb', {
      bg: '#55595c',
      fg: '#eceeef',
      text: 'Thumbnail'
    });
</script>
</body>
</html>

catalog/templates/catalog/data.html
{% extends 'catalog/base.html' %}
{% load custom_tags %}
{% block content %}
<div class="container">
    <div class="row">
        {% for object in object_list%}
        <div class="col-lg-4 card mb-4 box-shadow">
            <div class="card-deck mb-3 text-center">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                    </div>
                    <div class="card-body">
                        <img class="mb-2" src="{{ object.image|mediapath }}" alt="" width="250" height="250">
                        <a type="button" href="{% url 'catalog:desc' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Подробнее</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/desc.html
{% extends 'catalog/base.html' %}
{% block content %}
<title>Описание</title>
<div class="card-deck mb-3 text-center">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">Наименование - "{{ object.name }}"</h4>
            <h4 class="my-0 font-weight-normal">Описание     - "{{ object.description }}"</h4>
            <h4 class="my-0 font-weight-normal">Категория    - "{{ object.category }}"</h4>
            <h4 class="my-0 font-weight-normal">Цена         - "{{ object.price }}"</h4>
        </div>
    </div>
</div>
{% endblock %}